apiVersion: apps/v1
kind: Deployment
metadata:
  name: s7ivan-ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      svc: ui
  template:
    metadata:
      labels:
        app: weather
        svc: ui
    spec:
      containers:
      - name: s7ivan-ui
        image: devopseasylearning/tarzan-ui:v0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_HOST
          value: "auth"
        - name: AUTH_PORT
          value: "8080"
        - name: WEATHER_HOST
          value: "weather"
        - name:  WEATHER_PORT
          value: "5000"
        - name: REDIS_USER
          value: "redis"
        - name:  REDIS_PASSWORD
          value: "redis"
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1

--- 

apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: NodePort
  selector:
    svc: ui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
      protocol: TCP